# Understnding Data 
### I create this file to understand data and testing the cleaning process, before going to the processing in pipline

In [1]:
import pandas as pd 
import os

raw_csv = "../../data/raw/yemen_cars.csv"

if os.path.exists(raw_csv):
    df = pd.read_csv(raw_csv)
    print(df)

            name                                description   model  \
0        سامسونج                        2012, سامسونج, اخرى  2012.0
1    بي ام دبليو  2011, بي ام دبليو, الفئة X6, X6 xDrive40i  2011.0
2            NaN                                       2006  2006.0
3       شيفروليه                  2016, شيفروليه, سبارك, LT  2016.0
4            NaN            نفاخ هواء هونداي كيا وكاله جديد     NaN
..           ...                                        ...     ...
295       تويوتا                   2010, تويوتا, كامري, XLE  2010.0
296       تويوتا             2017, تويوتا, راف فور, Limited  2017.0
297       تويوتا                  2017, تويوتا, راف فور, SE  2017.0
298       تويوتا                    2005, تويوتا, برادو, VX  2005.0
299       تويوتا                    2011, تويوتا, برادو, TX  2011.0

      posted_at                                          image_url  \
0    2026-04-22  https://opensooq-images.os-cdn.com/previews/64...
1    2026-04-22  https://opensooq-images.os-cdn.com/previews/64...
2          الآن  https://opensooq-images.os-cdn.com/previews/64...
3    2026-04-22  https://opensooq-images.os-cdn.com/previews/64...
4    2026-04-22  https://opensooq-images.os-cdn.com/previews/64...
..          ...                                                ...
295  19-04-2026  https://opensooq-images.os-cdn.com/previews/64...
296  19-04-2026  https://opensooq-images.os-cdn.com/previews/64...
297  19-04-2026  https://opensooq-images.os-cdn.com/previews/64...
298  19-04-2026  https://opensooq-images.os-cdn.com/previews/64...
299  19-04-2026  https://opensooq-images.os-cdn.com/previews/64...

              price  status   mileage              location country
0    1,300,000 ريال  مستعمل    5499.5            نقم, صنعاء   Yemen
1    2,378,088 ريال  مستعمل  184999.5        الاصبحي, صنعاء   Yemen
2    3,500,000 ريال     NaN       NaN         أخرى, البيضاء   Yemen
3    1,101,430 ريال  مستعمل   64999.5       الحالي, الحديدة   Yemen
4       14,000 ريال    جديد       NaN       الحالي, الحديدة   Yemen
..              ...     ...       ...                   ...     ...
295  1,201,560 ريال  مستعمل  184999.5  الجراف الغربي, صنعاء   Yemen
296  4,305,590 ريال  مستعمل   44999.5        السبعين, صنعاء   Yemen
297  3,880,038 ريال  مستعمل   74999.5        السبعين, صنعاء   Yemen
298  3,129,063 ريال  مستعمل  200000.0              أخرى, إب   Yemen
299  8,000,000 ريال  مستعمل  154999.5              أخرى, إب   Yemen

[300 rows x 10 columns]

In [2]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 300 entries, 0 to 299
Data columns (total 10 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   name         233 non-null    str
 1   description  300 non-null    str
 2   model        274 non-null    float64
 3   posted_at    300 non-null    str
 4   image_url    300 non-null    str
 5   price        299 non-null    str
 6   status       285 non-null    str
 7   mileage      233 non-null    float64
 8   location     300 non-null    str
 9   country      300 non-null    str
dtypes: float64(2), str(8)
memory usage: 23.6 KB

In [3]:
df.describe()

             model        mileage
count   274.000000     233.000000
mean   2009.817518  107388.109442
std       8.068588   77952.622078
min    1970.000000       0.000000
25%    2006.000000   14999.500000
50%    2010.000000  124999.500000
75%    2014.000000  184999.500000
max    2026.000000  200000.000000

In [4]:
df.head()

,name,description,model,posted_at,image_url,price,status,mileage,location,country
0,سامسونج,"2012, سامسونج, اخرى",2012.0,2026-04-22,https://opensooq-images.os-cdn.com/previews/64...,"1,300,000 ريال",مستعمل,5499.5,"نقم, صنعاء",Yemen
1,بي ام دبليو,"2011, بي ام دبليو, الفئة X6, X6 xDrive40i",2011.0,2026-04-22,https://opensooq-images.os-cdn.com/previews/64...,"2,378,088 ريال",مستعمل,184999.5,"الاصبحي, صنعاء",Yemen
2,NaN,2006,2006.0,الآن,https://opensooq-images.os-cdn.com/previews/64...,"3,500,000 ريال",NaN,NaN,"أخرى, البيضاء",Yemen
3,شيفروليه,"2016, شيفروليه, سبارك, LT",2016.0,2026-04-22,https://opensooq-images.os-cdn.com/previews/64...,"1,101,430 ريال",مستعمل,64999.5,"الحالي, الحديدة",Yemen
4,NaN,نفاخ هواء هونداي كيا وكاله جديد,NaN,2026-04-22,https://opensooq-images.os-cdn.com/previews/64...,"14,000 ريال",جديد,NaN,"الحالي, الحديدة",Yemen

In [5]:
df.sample(5)

,name,description,model,posted_at,image_url,price,status,mileage,location,country
293,NaN,2005,2005.0,19-04-2026,https://opensooq-images.os-cdn.com/previews/64...,"600,000 ريال",NaN,NaN,"الجمارك, ذمار",Yemen
3,شيفروليه,"2016, شيفروليه, سبارك, LT",2016.0,2026-04-22,https://opensooq-images.os-cdn.com/previews/64...,"1,101,430 ريال",مستعمل,64999.5,"الحالي, الحديدة",Yemen
171,دايو,"2013, دايو, سوبر صالون",2013.0,أمس,https://opensooq-images.os-cdn.com/previews/64...,"2,400,000 ريال",مستعمل,174999.5,"أخرى, عمران",Yemen
5,تويوتا,"2013, تويوتا, كورولا, XLE",2013.0,2026-04-22,https://opensooq-images.os-cdn.com/previews/64...,"18,874,256 ريال",جديد,0.0,"السبعين, صنعاء",Yemen
282,NaN,2009,2009.0,19-04-2026,https://opensooq-images.os-cdn.com/previews/64...,"5,500 ريال",مستعمل,NaN,"قاع القيضي, صنعاء",Yemen

In [6]:
df.isna().sum()

name           67
description     0
model          26
posted_at       0
image_url       0
price           1
status         15
mileage        67
location        0
country         0
dtype: int64

In [7]:
df = df[df['name'].notna()]

In [8]:
df.isna().sum()

name           0
description    0
model          0
posted_at      0
image_url      0
price          1
status         0
mileage        0
location       0
country        0
dtype: int64

In [9]:
df['price'] = df['price'].replace(r"[^\d.]",'',regex= True)
df['price']=pd.to_numeric(df['price'])
df['price']= df['price'].fillna(df['price'].median())

df.isna().sum()

name           0
description    0
model          0
posted_at      0
image_url      0
price          0
status         0
mileage        0
location       0
country        0
dtype: int64

In [10]:
df[df.isnull().any(axis= 1)]

Empty DataFrame
Columns: [name, description, model, posted_at, image_url, price, status, mileage, location, country]
Index: []

In [11]:
type(df)

pandas.DataFrame

In [12]:
df = df.dropna()

In [13]:
df.isna().sum()

name           0
description    0
model          0
posted_at      0
image_url      0
price          0
status         0
mileage        0
location       0
country        0
dtype: int64

In [14]:
df.sample(10)

,name,description,model,posted_at,image_url,price,status,mileage,location,country
50,هيونداي,"2008, هيونداي, جيتز, Standard",2008.0,2026-04-22,https://opensooq-images.os-cdn.com/previews/64...,800000.0,مستعمل,200000.0,"الحثيلي, صنعاء",Yemen
287,تويوتا,"2010, تويوتا, لاند كروزر, VXR",2010.0,19-04-2026,https://opensooq-images.os-cdn.com/previews/64...,3254225.0,مستعمل,200000.0,"السبعين, صنعاء",Yemen
219,هيونداي,"2007, هيونداي, سنتافي, Limited",2007.0,أمس,https://opensooq-images.os-cdn.com/previews/64...,1677178.0,مستعمل,200000.0,"ميدان التحرير, صنعاء",Yemen
249,هيونداي,"2007, هيونداي, توسان, Limited",2007.0,19-04-2026,https://opensooq-images.os-cdn.com/previews/64...,1351755.0,جديد,0.0,"الجراف الشرقي, صنعاء",Yemen
251,هيونداي,"2010, هيونداي, توسان, Limited",2010.0,19-04-2026,https://opensooq-images.os-cdn.com/previews/64...,926203.0,مستعمل,94999.5,"الاصبحي, صنعاء",Yemen
47,تويوتا,"2010, تويوتا, يارس, S",2010.0,2026-04-22,https://opensooq-images.os-cdn.com/previews/64...,1001300.0,مستعمل,5499.5,"مديرية المعين, صنعاء",Yemen
9,هيونداي,"2005, هيونداي, النترا, GL",2005.0,2026-04-22,https://opensooq-images.os-cdn.com/previews/64...,600000.0,مستعمل,154999.5,"السبعين, صنعاء",Yemen
61,مرسيدس بنز,"2016, مرسيدس بنز, الفئة-E, E 350",2016.0,2026-04-22,https://opensooq-images.os-cdn.com/previews/64...,3254225.0,مستعمل,64999.5,"الاصبحي, صنعاء",Yemen
205,دايو,"2008, دايو, ماتيز",2008.0,أمس,https://opensooq-images.os-cdn.com/previews/64...,375488.0,مستعمل,200000.0,"أخرى, عدن",Yemen
23,تويوتا,"1989, تويوتا, لاند كروزر, GXR",1989.0,2026-04-22,https://opensooq-images.os-cdn.com/previews/64...,1839889.0,مستعمل,34999.5,"الظهار, إب",Yemen

In [15]:
douplicates = df[df.duplicated()]
douplicates

,name,description,model,posted_at,image_url,price,status,mileage,location,country
94,سامسونج,"2012, سامسونج, اخرى",2012.0,2026-04-22,https://opensooq-images.os-cdn.com/previews/64...,1300000.0,مستعمل,5499.5,"نقم, صنعاء",Yemen
106,بي ام دبليو,"2011, بي ام دبليو, الفئة X6, X6 xDrive40i",2011.0,2026-04-22,https://opensooq-images.os-cdn.com/previews/64...,2378088.0,مستعمل,184999.5,"الاصبحي, صنعاء",Yemen

In [16]:
hi = df[df['description'] == '2004, كرايسلر, اخرى']
hi.head(100)

Empty DataFrame
Columns: [name, description, model, posted_at, image_url, price, status, mileage, location, country]
Index: []

In [17]:
print(df["price"].describe())

count    2.330000e+02
mean     1.043330e+07
std      7.485816e+07
min      2.400000e+05
25%      1.001300e+06
50%      1.501950e+06
75%      2.202860e+06
max      7.831333e+08
Name: price, dtype: float64

In [18]:
df.info()

<class 'pandas.DataFrame'>
Index: 233 entries, 0 to 299
Data columns (total 10 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   name         233 non-null    str
 1   description  233 non-null    str
 2   model        233 non-null    float64
 3   posted_at    233 non-null    str
 4   image_url    233 non-null    str
 5   price        233 non-null    float64
 6   status       233 non-null    str
 7   mileage      233 non-null    float64
 8   location     233 non-null    str
 9   country      233 non-null    str
dtypes: float64(3), str(7)
memory usage: 20.0 KB